version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data/stocks.db:/app/stocks.db
    environment:
      - FLASK_SECRET_KEY=changeme
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}
      - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
      - MAILGUN_FROM=${MAILGUN_FROM}
